name: Auto-release on change

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  release:
    permissions: write-all
    defaults:
        run:
          working-directory: ./
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Build tarballs
        run: |
          sh ./create-tarballs.sh
    
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "filotimo-core-packages"
            files: |
              *.tar.gz
